### ISSUE TITLE
运行不起来

### ISSUE THREAD

**Issue by wchuan163** [JunFenngZhi/ORB-image_stitching#1]
好像运行不起来，有可以测试的运行文件吗

**Comment by JunFenngZhi** [comment]
你好。没有生成运行文件哎。可以提供一下报错信息吗？

**Comment by wchuan163** [comment]
Matching.BF_match  后 match_result.size()==0； 然后Mat H = My_RANSAC(match_result) 里飞了

**Comment by JunFenngZhi** [comment]
if (Match_List.size() <= 4)
	{
		cout << "匹配特征点对数太少！" << endl;
		system("pause");
	}
是卡在这里了吗？ match_result.size()=0说明两张图没有特征点可以匹配上，所以后续的RANSAC算法无法进行。

**Comment by wchuan163** [comment]
对的，应该是 BF_Match 里面没有匹配上

**Comment by JunFenngZhi** [comment]
可能两张图片差异过大了。
